/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#15803D",
        "primary-container": "#15803d",
        "primary-hover": "#166534",
        "primary-soft": "#DCFCE7",
        "on-primary": "#ffffff",
        "on-primary-container": "#d3ffd5",
        "background": "#F8FAFC",
        "surface": "#FFFFFF",
        "surface-tint": "#006d30",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "border": "#E2E8F0",
        "text": "#0F172A",
        "text-muted": "#475569",
        "text-disabled": "#94A3B8",
        "error": "#DC2626",
        "error-soft": "#FEE2E2",
        "warning": "#D97706",
        "warning-soft": "#FEF3C7",
        "secondary": "#515f74",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e3fc",
        "on-secondary-container": "#57657a",
        "outline": "#6f7a6e",
        "outline-variant": "#becabc",
        "on-surface": "#131b2e",
        "on-surface-variant": "#3f493f",
        "on-background": "#131b2e",
        // Semantic status badge tokens
        "badge-created-text": "#475569",
        "badge-created-bg": "#F1F5F9",
        "badge-collected-text": "#1D4ED8",
        "badge-collected-bg": "#DBEAFE",
        "badge-transit-text": "#B45309",
        "badge-transit-bg": "#FEF3C7",
        "badge-rts-text": "#6D28D9",
        "badge-rts-bg": "#EDE9FE",
        "badge-completed-text": "#15803D",
        "badge-completed-bg": "#DCFCE7",
        "badge-superseded-text": "#64748B",
        "badge-superseded-bg": "#F1F5F9",
        "badge-deleted-text": "#B91C1C",
        "badge-deleted-bg": "#FEE2E2",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "gutter": "1rem",
        "gutter-mobile": "0.75rem",
        "margin": "1.5rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "page-title": ["Inter", "sans-serif"],
        "section-title": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "body-medium": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "badge": ["Inter", "sans-serif"],
        "kpi-number": ["Inter", "sans-serif"],
        "batch-id": ["Inter", "monospace", "sans-serif"],
      },
      fontSize: {
        "page-title": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "section-title": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-medium": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "badge": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "kpi-number": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "batch-id": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
      }
    },
  },
  plugins: [],
}

